apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: hostpath
  hostPath:
    path: /home/thiha/pv-dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: frontend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   
  storageClassName: hostpath