apiVersion: v1
data:
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_HOSTNAME: d29yZHByZXNz
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: d29yZHByZXNz
  MYSQL_PASSWORD: d29yZHByZXNz
kind: Secret
metadata:
  creationTimestamp: "2024-10-05T05:55:46Z"
  name: mysql-var-secret
  namespace: db
  resourceVersion: "116947"
  uid: ceb4da31-2866-4374-a47e-814e2d596109
type: Opaque
